### ISSUE TITLE
Hard-coded non-English string in the English UI - Tamanho do vídeo 

### ISSUE THREAD

**Issue by mudrd8mz** [EduardoKrausME/moodle-mod_supervideo#1]
![image](https://user-images.githubusercontent.com/85831/78015414-a9fda280-7349-11ea-9330-5b2557c9b6b1.png)

**Comment by eduardokraus** [comment]
https://github.com/EduardoKrausME/moodle-mod_supervideo/commit/4c5f89a610c99c8b537b79891e1e44a3bd9a25dc
