### ISSUE TITLE
Activity completion doesn't seem to be working correctly

### ISSUE THREAD

**Issue by luisgbo20** [EduardoKrausME/moodle-mod_supervideo#14]
According to the comments on the moodle page, version 4.2 works, but I can't update my theme limitation.

I tested it in version 4.0.9 and 4.1.4 and the registration of the percentage viewed does not work nor the function to mark completed when viewed 90%

**Comment by eduardokraus** [comment]
Problem solved

**Comment by luisgbo20** [comment]
Tks @eduardokraus I tested it here and it's running perfectly, thank you very much

An observation, in the report the percentage is displayed correctly, but in the class when leaving and returning it shows 1% again, I don't know if it would be a bug or an improvement.
