### ISSUE TITLE
formatTime function is not defined in PHP

### ISSUE THREAD

**Issue by sokunthearithmakara** [EduardoKrausME/moodle-mod_supervideo#19]
In the lib.php file, the formatTIme function was not defined which caused an error when viewing Complete Report.

![image](https://github.com/EduardoKrausME/moodle-mod_supervideo/assets/16877863/4d1b4162-32cb-4880-a061-483c83de53b5)

**Comment by eduardokraus** [comment]
https://github.com/EduardoKrausME/moodle-mod_supervideo/commit/07ffe8648feb1590be1a1a247e29ee81f30c4928
