### ISSUE TITLE
A conclusão não funciona quando atrelado a nota e/ou porcentagem de progresso no vídeo

### ISSUE THREAD

**Issue by mel-oliveira** [EduardoKrausME/moodle-mod_supervideo#20]
Boa tarde, Eduardo
tudo bem ?

estou testando o plugin na versão do moodle 3.9 e ao configurar o recurso para atribuir a conclusão por nota e/ou porcentagem do progresso no vídeo ,  ele não atribui a conclusão para o cursista.

![image](https://github.com/EduardoKrausME/moodle-mod_supervideo/assets/81819885/74f78260-5a7a-4741-9cc0-9f70876390c7)

![image](https://github.com/EduardoKrausME/moodle-mod_supervideo/assets/81819885/afc0bc98-38f6-4157-8f70-deaa2b0f93a5)

A conclusão só esta sendo marcada se eu considerar somente a visualização do recurso, nao garantido assim se aluno assistiu ou não o vídeo.

![image](https://github.com/EduardoKrausME/moodle-mod_supervideo/assets/81819885/08f200ff-cedf-49f8-8780-18afc5233f9c)

Será que pode me ajudar ??

Att

**Comment by eduardokraus** [comment]
Vou ter que fazer uma análise

**Comment by xeviux** [comment]
Same issue here, i have 3.9.2+ version

**Comment by eduardokraus** [comment]
Foi corrigido
