### ISSUE TITLE
error adding super video 

### ISSUE THREAD

**Issue by Smartlearn-edu** [EduardoKrausME/moodle-mod_supervideo#24]
on moodle 4.3 
postges13 ,php8.1
i git this error 
Error reading from database
debug :
Script /course/mod.php?id=558&add=supervideo§ion=0&sr=0&beforemod=0 mutated the session after it was closed: $SESSION->editedpages

    line 791 of /lib/classes/session/manager.php: call to debugging()
    line 159 of /lib/classes/shutdown_manager.php: call to core\session\manager::check_mutated_closed_session()
    line ? of unknownfile: call to core_shutdown_manager::shutdown_handler() 

Debug info: ERROR: invalid input syntax for type bigint: ""
SELECT f.id AS id, f.contenthash, f.pathnamehash, f.contextid, f.component, f.filearea, f.itemid, f.filepath, f.filename, f.userid, f.filesize, f.mimetype, f.status, f.source, f.author, f.license, f.timecreated, f.timemodified, f.sortorder, f.referencefileid, r.repositoryid AS repositoryid, r.reference AS reference, r.lastsync AS referencelastsync
FROM mdl_files f
LEFT JOIN mdl_files_reference r
ON f.referencefileid = r.id
WHERE f.contextid = $1
AND f.component = $2
AND f.filearea = $3

AND f.itemid = $4 ORDER BY itemid, filepath, filename
[array (
0 => 381,
1 => 'mod_supervideo',
2 => 'content',
3 => '',
)]
Error code: dmlreadexception Stack trace:

    line 494 of /lib/dml/moodle_database.php: dml_read_exception thrown
    line 293 of /lib/dml/moodle_read_slave_trait.php: call to moodle_database->query_end()
    line 358 of /lib/dml/pgsql_native_moodle_database.php: call to pgsql_native_moodle_database->read_slave_query_end()
    line 1044 of /lib/dml/pgsql_native_moodle_database.php: call to pgsql_native_moodle_database->query_end()
    line 667 of /lib/filestorage/file_storage.php: call to pgsql_native_moodle_database->get_records_sql()
    line 426 of /lib/filelib.php: call to file_storage->get_area_files()
    line 168 of /mod/supervideo/mod_form.php: call to file_prepare_draft_area()
    line 505 of /course/moodleform_mod.php: call to mod_supervideo_mod_form->data_preprocessing()
    line 162 of /course/modedit.php: call to moodleform_mod->set_data()

**Comment by eduardokraus** [comment]
https://github.com/EduardoKrausME/moodle-mod_supervideo/commit/5e4ebbfb0384b057cb46b7c09a77aaec2cf24f1e

**Comment by Smartlearn-edu** [comment]
thank you so much
it now opens and can play videos
but when try to use *Kapture,  * i got this error :

*Warning*: require_once(config.php): Failed to open stream: No such file or
directory in
*/home/smlearn/public_html/mod/supervideo/vendor/kapture/index.php* on line
*2*

*Fatal error*: Uncaught Error: Failed opening required 'config.php'
(include_path='.:') in
/home/smlearn/public_html/mod/supervideo/vendor/kapture/index.php:2 Stack
trace: #0 {main} thrown in
*/home/smlearn/public_html/mod/supervideo/vendor/kapture/index.php* on line
*2*
