### ISSUE TITLE
Videos do Vimeo pede login no app

### ISSUE THREAD

**Issue by thiagoserrao** [EduardoKrausME/moodle-mod_supervideo#25]
Os videos do Vimeo não são apresentados no aplicativo, é apresentado a tela de login, mesmo sem configuração de privacidade

Um exemplo é o video https://vimeo.com/939135094

<img src="https://github.com/EduardoKrausME/moodle-mod_supervideo/assets/20133836/845c0b27-a665-45cb-a033-cbc8160757db" width=250>

**Comment by eduardokraus** [comment]
Vídeo funcionou normal aqui.

![Captura de Tela 2024-05-07 às 21 33 10](https://github.com/EduardoKrausME/moodle-mod_supervideo/assets/7725236/af803774-cc81-426d-97d8-0f62f8f4d0e3)

**Comment by thiagoserrao** [comment]
Ola, acessando pela web sim funciona, o problema ocorre no aplicativo Moodle Mobile

**Comment by Hemersonass2** [comment]
Tiveram alguma resposta sobre o ocorrido?
