### ISSUE TITLE
Problem for other video provider

### ISSUE THREAD

**Issue by mathildemenoret** [EduardoKrausME/moodle-mod_supervideo#27]
Hello,
In many french universities, we are using a video provider named POD (french developpment, each university hosts its instance https://pod.esup-portail.org/ ).
Unfortunately the video does not play (for example: https://pod.enib.fr/media/videos/f0ee37a35749172589588415deb9cc530f2d446008ccafa064db17be7cad11a5/0595/720p.mp4 ) - it works for H5P though
Is there any way it could be fixed?
Thanks a lot!
Mathilde

**Comment by eduardokraus** [comment]
Bonjour Mathilde,

Merci d'avoir signalé ce problème. En testant localement, j'ai remarqué que la vidéo ne se lit pas en raison d'une erreur CORS (Cross-Origin Resource Sharing). Le navigateur bloque l'accès à la vidéo hébergée sur 'https://pod.enib.fr/' car l'en-tête 'Access-Control-Allow-Origin' n'est pas présent dans la réponse HTTP.

Pour résoudre ce problème, il sera nécessaire de contacter les administrateurs du POD, responsables de l'infrastructure d'hébergement de la vidéo. Ils devront configurer les en-têtes CORS appropriés sur les URL des vidéos, ce qui permettra leur lecture sur d'autres domaines, comme Moodle.

Si vous avez besoin d'une assistance supplémentaire ou de plus de détails techniques à fournir au support du POD, je suis à votre disposition pour vous aider.
![Uploading Captura de Tela 2024-07-11 às 10.35.33.png…]()
