### ISSUE TITLE
Video replacement bug: video doesn't change after upload new one

### ISSUE THREAD

**Issue by Karastel** [EduardoKrausME/moodle-mod_supervideo#28]
Steps to reproduce:

1. Add Super Video activity,
2. Upload video (for example - 1.mp4),
3. Save activity,
4. Open activity settings
5. Change the video
- delete video & upload new one (for example: delete 1.mp4 & upload 2.mp4),
- or upload new one with same name (for example: upload new video with same 1.mp4 name),
6. Save activity.

Video doesn't change. I steel see 1.mp4.

**Comment by eduardokraus** [comment]
Hi,

Thank you very much for reporting the bug! After investigating, I found out that the file was not saved correctly in the update. I also took the opportunity to implement an improvement by adding the `file_id` to the `file_url` path, ensuring that the cache will be cleared automatically when a file is replaced with the same name.

Thanks again for your help in making the platform better!

Best regards,
Eduardo Kraus
