### ISSUE TITLE
Problema ao acessar o Relatório dos estudantes

### ISSUE THREAD

**Issue by guilhermeceadufop** [EduardoKrausME/moodle-mod_supervideo#29]
Boa tarde Eduardo, 

Previamente já parabenizo pela implementação deste plugin que é extremamente útil.

Instalei o plugin há pouco e não estou conseguindo entrar no relatório da atividade SuperVídeo, além de não ser pontuado no quadro de notas da sala virtual. Possuo plataforma Moodle 3.9.25 e banco de dados PostgreSQL. Segue abaixo a mensagem de erro ao tentar abrir o relatório.

Erro ao ler a base de dados

Informações de depuração:  ERRO: coluna "sv.cm_id" deve aparecer na cláusula GROUP BY ou ser utilizada em uma função de agregação
LINE 1: SELECT sv.user_id, sv.cm_id, MAX(sv.currenttime) currenttime...
^
SELECT sv.user_id, sv.cm_id, MAX(sv.currenttime) currenttime, MAX(sv.duration) duration,
MAX(sv.percent) percent, MAX(sv.timecreated) timecreated,
u.firstname, u.lastname, u.email,
(
SELECT COUNT(*)
FROM mdl_supervideo_view sv1
WHERE sv1.cm_id = sv.cm_id
AND sv1.user_id = sv.user_id
AND sv1.percent > 0
) AS quantidade,
u.firstnamephonetic, u.lastnamephonetic, u.middlename, u.alternatename
FROM mdl_supervideo_view sv
JOIN mdl_user u ON u.id = sv.user_id
WHERE sv.cm_id = $1
GROUP BY sv.user_id
ORDER BY sv.user_id LIMIT 40
[array (
0 => '376667',
)]
Error code: dmlreadexception
Rastreamento de pilha: 
line 486 of /lib/dml/moodle_database.php: dml_read_exception thrown
line 329 of /lib/dml/pgsql_native_moodle_database.php: call to moodle_database->query_end()
line 826 of /lib/dml/pgsql_native_moodle_database.php: call to pgsql_native_moodle_database->query_end()
line 391 of /mod/supervideo/classes/report/supervideo_view.php: call to pgsql_native_moodle_database->get_recordset_sql()
line 2039 of /lib/tablelib.php: call to mod_supervideo\report\supervideo_view->query_db()
line 67 of /mod/supervideo/report.php: call to table_sql->out()

Desde já agradeço a atenção dispensada.

Att.

**Comment by eduardokraus** [comment]
Você poderia atualizar e testar?

**Comment by guilhermeceadufop** [comment]
Boa tarde Eduardo,

Espero que esteja bem!

Conforme solicitado, fiz a atualização para a versão 2.6.9 (2024081402).
Continua gerando erro, segue o retorno do debug abaixo.
----------------------------------------------------------------------------------------------------------------------------------------
Informações de depuração:  ERRO: erro de sintaxe em ou próximo a "LIMIT"
LINE 35: LIMIT 40 LIMIT 40
^

SELECT
sv.user_id,
sv.cm_id,
MAX(sv.currenttime) AS currenttime,
MAX(sv.duration) AS duration,
MAX(sv.percent) AS percent,
MAX(sv.timecreated) AS timecreated,
u.firstname,
u.lastname,
u.email,
(
SELECT COUNT(*)
FROM mdl_supervideo_view sv1
WHERE sv1.cm_id = sv.cm_id
AND sv1.user_id = sv.user_id
AND sv1.percent > 0
) AS quantidade,
u.firstnamephonetic,
u.lastnamephonetic,
u.middlename,
u.alternatename
FROM
mdl_supervideo_view sv
JOIN
mdl_user u ON u.id = sv.user_id
WHERE
sv.cm_id = $1
GROUP BY
sv.user_id, sv.cm_id,
u.firstname, u.lastname, u.email,
u.firstnamephonetic, u.lastnamephonetic, u.middlename, u.alternatename
ORDER BY
sv.user_id
LIMIT 40 LIMIT 40
[array (
0 => '391188',
)]
Error code: dmlreadexception
Rastreamento de pilha:

   - line 486 of /lib/dml/moodle_database.php: dml_read_exception thrown
   - line 329 of /lib/dml/pgsql_native_moodle_database.php: call to
   moodle_database->query_end()
   - line 826 of /lib/dml/pgsql_native_moodle_database.php: call to
   pgsql_native_moodle_database->query_end()
   - line 521 of /mod/supervideo/classes/report/supervideo_view.php: call
   to pgsql_native_moodle_database->get_recordset_sql()
   - line 313 of /mod/supervideo/classes/report/supervideo_view.php: call
   to mod_supervideo\report\supervideo_view->query_db_postgresql()
   - line 2039 of /lib/tablelib.php: call to
   mod_supervideo\report\supervideo_view->query_db()
   - line 67 of /mod/supervideo/report.php: call to table_sql->out()

----------------------------------------------------------------------------------------------------------------------------------------

Desde já agradeço a atenção dispensada.


Em qua., 14 de ago. de 2024 às 11:59, Eduardo Kraus <
***@***.***> escreveu:

**Comment by eduardokraus** [comment]
https://moodle.org/plugins/mod_supervideo/2.6.10/32827

**Comment by guilhermeceadufop** [comment]
Bom dia Eduardo,

Espero que esteja bem!

Excelente, agora está funcionando perfeitamente. Muitíssimo obrigado pelo
empenho na solução do erro.

E novamente parabéns pelo desenvolvimento do plugin!


*Atenciosamente,*

*Guilherme José Anselmo Moreira.*


Em qui., 15 de ago. de 2024 às 18:45, Eduardo Kraus <
***@***.***> escreveu:

**Comment by guilhermeceadufop** [comment]
Boa tarde Eduardo,

Espero que esteja bem!

Ao receber o feedback de alguns professores, eles informaram que na
Conclusão de atividade as opções Requer nota e/ou Requer porcentagem não
tem sido considerado para marcar como atividade concluída. Somente tem
funcionado a opção Requer visualização que basta o estudante abrir a
atividade para considerar concluída.
Outro ponto é a pontuação que tem apresentado inconsistência. Mesmo o
estudante visualizando 100% do vídeo, no relatório de notas consta como
abaixo dos 100%, segue abaixo alguns prints para auxiliar no entendimento.

[image: SuperVideo1.jpeg]
[image: SuperVideo2.jpeg]

Vale salientar que é algo que não gera mensagem de erro.

Desde já agradeço a atenção e o empenho na solução dos problemas.


*Atenciosamente,*


*
<https://cead.ufop.br/index.php/contato/36-lista-de-contatos/1997-servidores-em-teletrabalho-pdg>*


Em sex., 16 de ago. de 2024 às 09:20, GUILHERME JOSE ANSELMO MOREIRA <
***@***.***> escreveu:
