### ISSUE TITLE
Can't upload  MP3, MP4 or WebM file

### ISSUE THREAD

**Issue by wuhsun** [EduardoKrausME/moodle-mod_supervideo#31]
The new version of Super Video cannot select “Or an MP3, MP4, or WebM file” as a video source. When clicking the “Save and display” button after uploading a video file, the error message “- You must supply a value here.” appears below the column labeled “YouTube, Vimeo, Google Drive, external link with MP4/MP3/M3U8/WebM extension, or an MP4/MP3/WebM file.”

**Comment by eduardokraus** [comment]
Hello,

Thank you for your feedback regarding the new version of Super Video. After conducting some tests, I was unable to reproduce the error mentioned. Please see the screenshots below that demonstrate the correct functioning of the feature.

If you are still experiencing the issue, please provide more details, such as the type of file you are trying to upload or the exact version of the plugin you are using. This way, I can assist you better.

Thank you!

![Captura de Tela 2024-08-31 às 21 47 54](https://github.com/user-attachments/assets/c284e5d9-c5d1-4ada-bb22-f209f91e99aa)
![Captura de Tela 2024-08-31 às 21 48 21](https://github.com/user-attachments/assets/b46c8cf6-be85-4260-9a06-a658528c69aa)
![Captura de Tela 2024-08-31 às 21 50 09](https://github.com/user-attachments/assets/5dda3f03-de98-43bc-ae7a-653c87f558ae)

**Comment by wuhsun** [comment]
Hello,

Previously, I uploaded one of my MP4 files. This time, I downloaded a free MP4 file(https://www.pexels.com/zh-tw/download/video/10661502/)  from the internet, but the result is still the same.
![upload_mp4_File](https://github.com/user-attachments/assets/dd41ea28-0427-49e7-b3c7-f5d1b53f3458)

My moodle platform are Moodle 4.1.12+ (Build: 20240823) and 4.1.9+ (Build: 20240320).

There was a similar comment in https://moodle.org/plugins/mod_supervideo on 2024/7/31, too.
