### ISSUE TITLE
Can't play m3u8 on Windows and Android

### ISSUE THREAD

**Issue by kackey621** [EduardoKrausME/moodle-mod_supervideo#33]
Hello, @eduardokraus  and @sokunthearithmakara 

Thanks for providing Super Video as open source.
SuperVideo can't play m3u8.
However, direct player such as hls.js and video.js can play.

[Environment]
- Windows / Android
- Chrome

![image](https://github.com/user-attachments/assets/7d59375b-a22d-43a7-882c-344a9b2845d6)

**Comment by eduardokraus** [comment]
Check if your error is not the same as this one here: https://github.com/EduardoKrausME/moodle-mod_supervideo/issues/27
