### ISSUE TITLE
Can't play video on iOS-app

### ISSUE THREAD

**Issue by vinnio** [EduardoKrausME/moodle-mod_supervideo#36]
When a video is added to a section, the activity can be viewed using a computer, laptop and Android App. But the iOS-app has problems with playing this. 
Moodle keeps requesting to login, when opening the Super Video activity. Even with cross-website tracking enabled.

**Comment by vinnio** [comment]
This can be solved using the changes as proposed in issue #35

**Comment by eduardokraus** [comment]
https://github.com/EduardoKrausME/moodle-mod_supervideo/issues/35
