### ISSUE TITLE
Video's from Google Drive are not working

### ISSUE THREAD

**Issue by vinnio** [EduardoKrausME/moodle-mod_supervideo#41]
When adding a Super Video activity, a video from Google drive is not working. It shows "Can't open the file."
Sharing settings of the video are open for everyone.
Version: 
2.6.17, 2024101000
Moodle 4.5 (Build: 20241007)

Also when using "video file URL" option in stead of the Google Drive-option, it shows an error: Not able to play, unsupported format.

**Comment by eduardokraus** [comment]
Version 2.6.19 fixes the issue.
