### ISSUE TITLE
Erros ao utilzar qualquer versão posterior a versão 2.6.13 no moodle 4.1

### ISSUE THREAD

**Issue by emersonpmartins** [EduardoKrausME/moodle-mod_supervideo#43]
A partir da versão 2.6.17 aparece o erro abaixo no moodle versão 4.1
![image](https://github.com/user-attachments/assets/c54570cd-7b6e-482f-9309-641ce4d0ec82)

**Comment by eduardokraus** [comment]
@emersonpmartins Limpe o cache ou verifique se tem CDN fazendo cache

**Comment by emersonpmartins** [comment]
Eduardo, boa tarde! Muito obrigado pelo seu suporte! Tudo funcionando perfeitamente!
