### ISSUE TITLE
Google Video - não apresenta conforme esperado

### ISSUE THREAD

**Issue by suifbr** [EduardoKrausME/moodle-mod_supervideo#44]
Olá Eduardo,
Quando inserimos um vídeo que está hospedado no Google Drive, encontramos alguns pontos:
- Mesmo escolhendo a proporção 16x9 o palco de exibição apresenta um quadro 3x4;
- Não é apresentada a barra de visualização dos vídeos
- No relatório não mostra o percentual de quanto o estudante assistiu

**Comment by eduardokraus** [comment]
Para Google Drive não tem a barra por falta de suporte do Google Drive
