### ISSUE TITLE
Version 2.6.21 (2024101900)

### ISSUE THREAD

**Issue by optical65** [EduardoKrausME/moodle-mod_supervideo#45]
This version don't work on moodle 4.4

**Comment by Buda9** [comment]
yes, actually, youtube videos are not loading properly

**Comment by optical65** [comment]
This Error with Vimeo  

1. You aborted the video playback.
2. A network error caused the video download to fail part-way.
3. The video playback was aborted due to a corruption problem or because the video used features your browser did not support.
4. The video could not be loaded, either because the server or network failed or because the format is not supported.
5. An unknown error occurred.

With versione 2.19 all ok

**Comment by optical65** [comment]
If I use a vimeo link it doesn't work. If I use a simple link it works but individual errors are reported
![erro_supervideo](https://github.com/user-attachments/assets/b05a48bd-a048-446f-8077-597a361f130f)

**Comment by eduardokraus** [comment]
The CSS that hides these errors may not be loading correctly. Therefore, I made a modification in the JavaScript to hide the error messages.

**Comment by eduardokraus** [comment]
I just realized that the correct name is "CSS," which should be read as "styleS," and not just "style."
