### ISSUE TITLE
Problem displaying videos MP4 and youtube

### ISSUE THREAD

**Issue by pxnqn** [EduardoKrausME/moodle-mod_supervideo#46]
Hi!

Thanks for the Supervideo plugin, really is usefull for me.

I have a problem with the image size displaying videos, they are not adjunting to screen and can´t make scroll.

Was tested with theme Boost.

This occurs with MP4 video, Moodle 4.5:
![image](https://github.com/user-attachments/assets/9f8fdabc-0114-4151-8441-a51ece03407a)

This occurs with Youtube videos, Moodle 4.04
![error moodle 4](https://github.com/user-attachments/assets/35c1bdcf-7f1d-4f15-9bf6-35ae304c312d)

I keep in contact if you need more details or access my site. 

Regards!

**Comment by eduardokraus** [comment]
https://moodle.org/plugins/mod_supervideo/2.6.23/33558

**Comment by Buda9** [comment]
Sorry @eduardokraus but it's still not working correctly. It works if we add:

#supervideo_area_embed {
    min-height: 570px;
}
