### ISSUE TITLE
invalid/hand-rolled install.xml

### ISSUE THREAD

**Issue by danmarsden** [EduardoKrausME/moodle-mod_supervideo#5]
The install.xml is no longer valid and was either created for an old version of Moodle or has been handwritten.
(note this was reported in a previous review of your plugin and mentioned in the Moodle tracker issue.)

This needs to be fixed using the Moodle xmldb editor (under admin > development > XMLDB.)

Please hit the "load" link for your plugin install.xml file in the moodle xmldb editor, and then make Moodle think there is an update to the file (easiest way to do this is to change the description of a table - add a full stop or something similar.) Then get XMLDB to "Save" the updated file which will remove all the old invalid xml from your file.

**Comment by eduardokraus** [comment]
sorted out
