### ISSUE TITLE
postgres support is a requirement for plugins db approval

### ISSUE THREAD

**Issue by danmarsden** [EduardoKrausME/moodle-mod_supervideo#8]
I'm guessing (but didn't test) this query will fail in postgres:
https://github.com/EduardoKrausME/moodle-mod_supervideo/blob/master/classes/report/supervideo_view.php#L318-L332

but there could be other queries in your plugin that don't work - it would be preferable that you test the plugin on a postgres install yourself (rather than relying on the plugin review team being the first to do this.)

**Comment by eduardokraus** [comment]
Fixed and tested with: https://extendsclass.com/postgresql-online.html

**Comment by danmarsden** [comment]
can't see any changes to that script in github, but maybe you haven't pushed your changes yet? - I'd expect Postgres to complain about the group by statement not including  sv.cm_id

**Comment by eduardokraus** [comment]
only https://github.com/EduardoKrausME/moodle-mod_supervideo/blob/master/classes/report/supervideo_view.php#L330
